export const ACHIEVEMENTS = [
  { name: "Lea Salonga", category: "Musika", tags: ["Babae"], description: "Filipina singer and actress. Tony Award winner for Miss Saigon. The singing voice of Disney's Mulan and Jasmine.", why: "Isang babaeng Pilipino na nagwagi sa mga entablado ng mundo at naging boses ng mga minamahal na bayani — patunay na ang talento ay lumalampas sa lahat ng hangganan." },
  { name: "Regine Velasquez", category: "Musika", tags: ["Babae"], description: "Known as 'Asia's Songbird.' One of the Philippines' most awarded singers.", why: "Isang babaeng naging pamantayan ng kahusayan sa musika sa bansang kung saan ang musika ay buhay." },
  { name: "Gloc-9", category: "Musika", tags: ["Lalaki"], description: "Rapper known for 'Sirena' and 'Upuan.' His song 'Sirena' tells the story of a father learning to accept his gay child.", why: "Isang lalaki sa hip-hop — isang larangang kilala sa hypermasculinity — na ginamit ang kanyang plataporma para sa pagtanggap sa LGBTQ+." },
  { name: "Alice Reyes", category: "Sayaw", tags: ["Babae"], description: "National Artist for Dance. Founded Ballet Philippines. Brought Filipino stories to ballet.", why: "Isang babaeng nagtayo ng institusyon at ginawang Pilipino ang ballet." },
  { name: "Francisca Reyes-Aquino", category: "Sayaw", tags: ["Babae"], description: "National Artist. Documented and preserved Philippine folk dances from across the country.", why: "Isang babaeng nagsiguro na ang mga katutubong sayaw — na kadalasang dinadala ng kababaihan — ay hindi mawawala." },
  { name: "Nonoy Froilan", category: "Sayaw", tags: ["Lalaki"], description: "Ballet dancer and actor. One of the Philippines' most respected male ballet dancers.", why: "Isang lalaki sa ballet — isang larangang madalas ituring na pambabae — na nagpatunay na ang biyaya ay walang kasarian." },
  { name: "Lualhati Bautista", category: "Panitikan", tags: ["Babae"], description: "Author of 'Dekada '70,' 'Gapo,' and 'Bata, Bata... Pa'no Ka Ginawa?' Her novels center on women's lives under martial law.", why: "Isang babaeng isinulat ang mga kuwento ng kababaihan sa pambansang memorya — na nagpapatunay na ang buhay ng kababaihan ay kasaysayan rin." },
  { name: "Marjorie Evasco", category: "Panitikan", tags: ["Babae"], description: "Filipina poet and essayist known for feminist and ecofeminist poetry.", why: "Isang babaeng nagsusulat sa Cebuano at Ingles, na nagpapatunay na ang panloob na buhay ng kababaihan ay karapat-dapat sa tula." },
  { name: "Danton Remoto", category: "Panitikan", tags: ["LGBTQIA+"], description: "Writer, professor, and LGBTQ+ advocate. Founder of Ang Ladlad, the first LGBTQ+ party-list in the Philippines.", why: "Isang lantarang gay na manunulat na ginawang adbokasiya ang kanyang sining para sa mga LGBTQ+ na Pilipino." },
  { name: "Pacita Abad", category: "Sining", tags: ["Babae"], description: "Filipina painter known for her vibrant trapunto paintings. One of Southeast Asia's most important modern artists.", why: "Isang babaeng tumanggi na makulong sa isang midyum o bansa, na gumawa ng sining na nagdiriwang ng kulay, migrasyon, at pagkakakilanlan." },
  { name: "Lino Brocka", category: "Sining", tags: ["Lalaki"], description: "National Artist for Film. Directed 'Maynila: Sa Mga Kuko ng Liwanag' and 'Tinimbang Ka Ngunit Kulang.' Made films about marginalized people.", why: "Isang lalaking ginamit ang sinehan upang ikuwento ang buhay ng mahihirap, ng mga itinakwil, at ng LGBTQ+ — noong walang ibang gumagawa nito." },
  { name: "Kidlat Tahimik", category: "Sining", tags: ["Katutubo"], description: "Filmmaker and artist. Known as the 'father of Philippine independent cinema.' Identifies with his Igorot heritage.", why: "Isang artistang tumanggi sa kolonyal na pamantayan sa pelikula at muling kinilala ang katutubong pagkakakilanlan bilang pinagmumulan ng pagmamalaki." },
  { name: "Fe del Mundo", category: "Agham", tags: ["Babae"], description: "Pediatrician. First woman admitted to Harvard Medical School. Founded the first pediatric hospital in the Philippines.", why: "Isang babaeng sumira sa hadlang ng kasarian sa Harvard at inialay ang buhay sa kalusugan ng mga bata." },
  { name: "Lourdes Cruz", category: "Agham", tags: ["Babae"], description: "National Scientist. Biochemist known for her work on cone snail toxins that led to painkillers.", why: "Isang babae sa larangang kung saan kakaunti pa rin ang kababaihan, na nagpapatunay na ang agham ay walang kasarian." },
  { name: "Gregorio Zara", category: "Agham", tags: ["Lalaki"], description: "Inventor of the videophone and other technological innovations. National Scientist.", why: "Isang Pilipinong siyentipiko na nagpakitang ang inobasyon ay maaaring magmula sa kahit saan, hindi lamang sa Kanluran." },
  { name: "Josefa Llanes Escoda", category: "Aktibismo", tags: ["Babae"], description: "Suffragist, social worker, and founder of the Girl Scouts of the Philippines. Killed during WWII.", why: "Isang babaeng nakipaglaban para sa karapatan ng kababaihan na bumoto at namatay para sa bayan." },
  { name: "Lorena Barros", category: "Aktibismo", tags: ["Babae"], description: "Founder of MAKIBAKA, a women's liberation movement. Killed at 26 during martial law.", why: "Isang babaeng nagpumilit na ang pagpapalaya ng kababaihan at ng bansa ay magkasama." },
  { name: "Maria Ressa", category: "Aktibismo", tags: ["Babae"], description: "Journalist. Nobel Peace Prize laureate. Co-founder of Rappler.", why: "Isang babaeng tumindig laban sa kapangyarihan at nagpakitang ang kalayaan sa pamamahayag ay isyu rin ng kababaihan." },
  { name: "Apo Whang-Od", category: "Katutubo", tags: ["Babae", "Katutubo"], description: "Kalinga tattoo artist. The last mambabatok of her generation. Continues to tattoo at over 100 years old.", why: "Isang babaeng nagdadala ng sinaunang tradisyon ng batok at nagpapatunay na ang katutubong kababaihan ay tagapag-ingat ng kasaysayan." },
  { name: "Macli-ing Dulag", category: "Katutubo", tags: ["Lalaki", "Katutubo"], description: "Kalinga leader who opposed the Chico Dam project. Killed for his resistance in 1980.", why: "Isang katutubong lalaki na namatay sa pagtatanggol sa lupa at paraan ng pamumuhay ng kanyang mga tao." },
  { name: "Bai Bibyaon Ligkayan Bigkay", category: "Katutubo", tags: ["Babae", "Katutubo"], description: "Manobo woman leader. Fought for indigenous land rights in Mindanao for decades.", why: "Isang babaeng pinuno sa kilusang madalas iugnay sa kalalakihan, na nagpapatunay na ang katutubong kababaihan ay namumuno rin." },
  { name: "Geraldine Roman", category: "LGBTQIA+", tags: ["LGBTQIA+"], description: "First openly transgender person elected to the Philippine House of Representatives (2016).", why: "Isang babaeng trans na pumasok sa kapangyarihang pampulitika at nagpakitang ang mga LGBTQ+ Pilipino ay nabibilang sa bawat silid." },
  { name: "Jake Zyrus", category: "LGBTQIA+", tags: ["LGBTQIA+"], description: "Trans man and singer. Formerly known internationally as Charice. Came out publicly and continues to make music.", why: "Isang trans na lalaki na bukas na namumuhay sa bansang kung saan ang mga trans ay nakararanas pa rin ng diskriminasyon — nagpapakita na ang pagiging totoo ay posible." },
  { name: "Boy Abunda", category: "LGBTQIA+", tags: ["LGBTQIA+"], description: "Television host and talent manager. One of the Philippines' most recognized openly gay public figures.", why: "Isang gay na lalaki na naging kilalang-kilala sa pamamagitan ng pagiging lubos na sarili — nagpapatunay na ang visibility ay nagbabago ng kultura." }
];

if (typeof window !== 'undefined') {
  window.ACHIEVEMENTS = ACHIEVEMENTS;
}
